### ISSUE TITLE
When deploying with war file, the bpmn.xml is not included

### ISSUE THREAD

**Issue by GoogleCodeExporter** [jeewan2015/grails-activiti-plugin#19]
```
What steps will reproduce the problem?
1. Run grails prod tomcat deploy
2. Run the workflow


What is the expected output? What do you see instead?
The workflow should work properly, similar to grails run-app. Instead an 
exception will be thrown:
2011-07-26 08:49:10,469 [http-bio-8089-exec-5] ERROR interceptor.CommandContext 
 - Error while closing command context
org.activiti.engine.ActivitiException: no processes deployed with key 'XXXX'
    at org.activiti.engine.impl.persistence.deploy.DeploymentCache.findDeployedLatestProcessDefinitionByKey(DeploymentCache.java:62)
    at org.activiti.engine.impl.cmd.StartProcessInstanceCmd.execute(StartProcessInstanceCmd.java:56)
    at org.activiti.engine.impl.cmd.StartProcessInstanceCmd.execute(StartProcessInstanceCmd.java:30)
    at org.activiti.engine.impl.interceptor.CommandExecutorImpl.execute(CommandExecutorImpl.java:24)
    at org.activiti.engine.impl.interceptor.CommandContextInterceptor.execute(CommandContextInterceptor.java:4

What version of the product are you using? On what operating system?
Grails Activiti plugin 5.6

Please provide any additional information below.


```

Original issue reported on code.google.com by `tmcchan...@gmail.com` on 26 Jul 2011 at 1:04

**Comment by GoogleCodeExporter** [comment]
```
key 'XXXX'? May I know which grails version are you using? Try this command: 
grails -DdisabledActiviti=true war
```

Original comment by `limchee...@vobject.com` on 26 Jul 2011 at 2:24

**Comment by GoogleCodeExporter** [comment]
```
I'm using Grails 1.3.7

1. I have masked out the key
2. I have tried the command and it still throw the same exception 
```

Original comment by `tmcchan...@gmail.com` on 26 Jul 2011 at 9:22

**Comment by GoogleCodeExporter** [comment]
```
I think the configuration at Config.groovy is not complete. It should have been:
    deploymentResources = ["file:./grails-app/conf/**/*.bpmn*.xml",
            "file:./grails-app/conf/**/*.png",
            "file:./src/taskforms/**/*.form",
            "classpath*:*.bpmn*.xml"]
The .bpmn*.xml files are copied to <webapp>/WEB-INF/classes which is in the 
classpath. Since the deploymentResource configuration does not have the 
classpath in the settings, the workflow definition could not be found.
```

Original comment by `tmcchan...@gmail.com` on 26 Jul 2011 at 9:36

**Comment by GoogleCodeExporter** [comment]
```
So, you solve this issue by adding "classpath*:*.bpmn*.xml" to Config.groovy? 
Alternatively, you can deploy the process resources such as bpmn20.xml manually 
using command "grails prod deploy-bar"
```

Original comment by `limchee...@vobject.com` on 26 Jul 2011 at 10:46
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Hi,

Yes, I've added the classpath for war
```

Original comment by `tmcchan...@gmail.com` on 26 Jul 2011 at 11:26

**Comment by GoogleCodeExporter** [comment]
```
Noted and thanks. As there is alternative solution, I will leave it.
```

Original comment by `limchee...@vobject.com` on 27 Jul 2011 at 3:09
- Changed state: **WontFix**
